giuh_time_scaling
NOAA-OWP/LGAR-C pull request #10
Opened 2023-07-13 21:12 UTC by ajkhattak

The PR fixes GIUH time scaling reported in the [issue](https://github.com/NOAA-OWP/LGAR-C/issues/8). The giuh ordinates from percentage per hour are scaled to account for LGAR model timestep.

## Additions
- Modified the Initialized function to extend the GIUH array for the scaled values

## Removals
- None

## Changes
- no significant changes other than modified giuh array at the initialization time

## Testing

1. Done 

## Screenshots
The giuh runoff using the old code has a high peak and quick recession, while the new code (taking into account time scaling) has a lower peak and relatively smooth rising and falling limbs, which makes sense.

![giuh_runoff_comparison](https://github.com/NOAA-OWP/LGAR-C/assets/15165757/b0c41db6-b1b1-4f3b-b923-26efe8e1b23a)

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Passes all existing automated tests
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

2023-07-13 21:19 UTC, PhilMiller requested changes

2023-07-13 21:19 UTC, PhilMiller commented on src/lgar.cxx
> +    giuh_ordinates_temp = NULL;
This is a memory leak - the allocation is never `delete[]`'d

Use `std::vector<double>` instead

2023-07-13 21:19 UTC, PhilMiller commented on src/lgar.cxx
> +  int num_giuh_ordinates_temp;
```suggestion
  // a temporary array to store the original (hourly based) giuh values
  std::vector<double> giuh_ordinates_temp;
```

2023-07-13 21:19 UTC, PhilMiller commented on src/lgar.cxx
> +      giuh_ordinates_temp = new double[vec.size()+1];
```suggestion
      giuh_ordinates_temp.resize(vec.size()+1);
```

2023-07-13 21:19 UTC, PhilMiller commented on src/lgar.cxx
> +    giuh_ordinates_temp = NULL;
If the code really needs the memory back right at this point, it should then call
```suggestion
    giuh_ordinates_temp.clear();
```

2023-07-13 22:15 UTC, ajkhattak commented
@PhilMiller Thanks Phil for your suggestions, they have been incorporated. please have a look and see if you have more suggestions. Although I added you as a reviewer by mistake, it turned out to be a useful mistake. Appreciate it!

2023-07-14 00:49 UTC, PhilMiller commented
You're welcome. I'm happy to help.

And no worries, you didn't accidentally add me as a reviewer - I'm a newcomer to the NWM enterprise, subscribed to activity on a bunch of the NOAA-OWP repositories. I skim whatever PRs I see come up as a way of gaining more fluency with the overall codebase.

2023-07-14 00:49 UTC, PhilMiller reviewed
I can't speak to the substance of the change, but the issue I saw is addressed, so no longer 'Request changes'

2023-07-14 01:43 UTC, merged

2023-07-14 01:47 UTC, peterlafollette commented
And thanks Phil for the suggestion!