updating LASAM to take field capacity as a parameter in the config file
NOAA-OWP/LGAR-C pull request #22
Opened 2024-04-05 00:32 UTC by peterlafollette

[Short description explaining the high-level reason for the pull request]

## Additions
In this PR, LASAM has been mildly refactored in order to have the field capacity be a user-specified parameter in the config file, in the same style as wilting point. I also updated the calibratable params list in bmi_lgar.hxx to include field capacity, as well as max ponded head. I also edited that list to not include vg_m and instead use vg_n, because the parameters file provides n rather than m.
-

## Removals

-

## Changes

-

## Testing

1.

## Screenshots

## Notes

-

## Todos

-

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist

### Target Environment support

- [ ] Windows
- [ ] Linux
- [ ] Browser

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

2024-04-11 17:26 UTC, ajkhattak requested changes
@peterlafollette have you tested if the newly added calibratable parameters are working properly? It looks to me that they are not, they are also not included in the calibratable params struct ([here](https://github.com/NOAA-OWP/LGAR-C/blob/PTL_add_field_capacity/include/all.hxx#L186))

2024-04-11 18:51 UTC, peterlafollette commented
Updated so that unit tests pass with n rather than m, will add max ponded depth and field capacity to unit test for calibration today / tomorrow

2024-04-12 02:55 UTC, peterlafollette commented
Updated so that unit test checks calibration for all calibratable variables, including n, max ponded depth, and field capacity.

2024-04-16 15:16 UTC, ajkhattak approved these changes
It looks good to me. Thanks @peterlafollette

2024-04-16 15:17 UTC, merged